// Generated types for Supabase database
// This file is automatically generated and should not be edited manually

export interface Database {
  public: {
    Tables: {
      // Define your database tables here
      users: {
        Row: {
          id: string
          created_at: string
          email: string
          // Add other user fields
        }
        Insert: {
          id?: string
          created_at?: string
          email: string
          // Add other user fields
        }
        Update: {
          id?: string
          created_at?: string
          email?: string
          // Add other user fields
        }
      }
      // Add other tables
    }
    Views: Record<string, unknown> // Define your database views here
    Functions: Record<string, unknown> // Define your database functions here
    Enums: Record<string, unknown> // Define your database enums here
  }
}