import type { StyleSpecification } from "maplibre-gl";
import { colors } from "@/styles/design-tokens";

const { map: m } = colors;

const textFr = [
  "coalesce",
  ["get", "name:fr"],
  ["get", "name"],
  ["get", "name:en"],
  ["get", "name:latin"],
] as const;

/** Landmark cities always labeled (tile place ranks alone are unreliable at FR zoom). */
const franceLandmarks = {
  type: "FeatureCollection" as const,
  features: [
    { name: "Paris", coordinates: [2.3522, 48.8566], rank: 1 },
    { name: "Versailles", coordinates: [2.1301, 48.8014], rank: 2 },
    { name: "Marseille", coordinates: [5.3698, 43.2965], rank: 1 },
    { name: "Lyon", coordinates: [4.8357, 45.764], rank: 1 },
    { name: "Toulouse", coordinates: [1.4442, 43.6047], rank: 1 },
    { name: "Nice", coordinates: [7.2619, 43.7102], rank: 1 },
    { name: "Nantes", coordinates: [-1.5536, 47.2184], rank: 1 },
    { name: "Strasbourg", coordinates: [7.7521, 48.5734], rank: 1 },
    { name: "Montpellier", coordinates: [3.8767, 43.6108], rank: 1 },
    { name: "Bordeaux", coordinates: [-0.5792, 44.8378], rank: 1 },
    { name: "Lille", coordinates: [3.0573, 50.6292], rank: 1 },
    { name: "Rennes", coordinates: [-1.6778, 48.1173], rank: 2 },
    { name: "Reims", coordinates: [4.0317, 49.2583], rank: 2 },
    { name: "Saint-Étienne", coordinates: [4.3872, 45.4397], rank: 2 },
    { name: "Toulon", coordinates: [5.928, 43.1242], rank: 2 },
    { name: "Grenoble", coordinates: [5.7245, 45.1885], rank: 2 },
    { name: "Dijon", coordinates: [5.0415, 47.322], rank: 2 },
    { name: "Angers", coordinates: [-0.5632, 47.4784], rank: 2 },
    { name: "Nîmes", coordinates: [4.3601, 43.8367], rank: 2 },
    { name: "Clermont-Ferrand", coordinates: [3.087, 45.7772], rank: 2 },
    { name: "Le Havre", coordinates: [0.1079, 49.4944], rank: 2 },
    { name: "Aix-en-Provence", coordinates: [5.4474, 43.5297], rank: 2 },
    { name: "Brest", coordinates: [-4.4861, 48.3908], rank: 2 },
    { name: "Limoges", coordinates: [1.2611, 45.8336], rank: 2 },
    { name: "Tours", coordinates: [0.6848, 47.3941], rank: 2 },
    { name: "Amiens", coordinates: [2.2957, 49.8942], rank: 2 },
    { name: "Perpignan", coordinates: [2.8956, 42.6886], rank: 2 },
    { name: "Metz", coordinates: [6.1757, 49.1193], rank: 2 },
    { name: "Besançon", coordinates: [6.0243, 47.2378], rank: 2 },
    { name: "Orléans", coordinates: [1.9093, 47.9029], rank: 2 },
    { name: "Rouen", coordinates: [1.0993, 49.4431], rank: 2 },
    { name: "Mulhouse", coordinates: [7.3398, 47.7508], rank: 2 },
    { name: "Caen", coordinates: [-0.3707, 49.1829], rank: 2 },
    { name: "Nancy", coordinates: [6.1844, 48.6921], rank: 2 },
  ].map(({ name, coordinates, rank }) => ({
    type: "Feature" as const,
    properties: { name, rank },
    geometry: { type: "Point" as const, coordinates },
  })),
};

/**
 * Modern FR-oriented basemap:
 * - terrain hillshade + landcover / water
 * - contrasted major roads (casing darker, fill lighter)
 * - reliable French city landmarks + tile place hierarchy
 */
const mapStyle: StyleSpecification = {
  version: 8,
  glyphs: "https://tiles.stadiamaps.com/fonts/{fontstack}/{range}.pbf",
  sources: {
    stadia: {
      type: "vector",
      url: "https://tiles.stadiamaps.com/data/openmaptiles.json",
    },
    terrain: {
      type: "raster-dem",
      tiles: [
        "https://s3.amazonaws.com/elevation-tiles-prod/terrarium/{z}/{x}/{y}.png",
      ],
      encoding: "terrarium",
      tileSize: 256,
      maxzoom: 15,
    },
    "fr-landmarks": {
      type: "geojson",
      data: franceLandmarks,
    },
  },
  layers: [
    {
      id: "background",
      type: "background",
      paint: { "background-color": m.background },
    },
    {
      id: "hillshade",
      type: "hillshade",
      source: "terrain",
      maxzoom: 15,
      paint: {
        "hillshade-shadow-color": m.hillshadeShadow,
        "hillshade-highlight-color": m.hillshadeHighlight,
        "hillshade-accent-color": m.hillshadeShadow,
        "hillshade-exaggeration": [
          "interpolate",
          ["linear"],
          ["zoom"],
          4,
          0.45,
          10,
          0.35,
          14,
          0.2,
        ],
        "hillshade-illumination-direction": 315,
      },
    },
    {
      id: "landcover-wood",
      type: "fill",
      source: "stadia",
      "source-layer": "landcover",
      minzoom: 3,
      filter: ["in", "class", "wood", "forest"],
      paint: {
        "fill-color": m.forest,
        "fill-opacity": [
          "interpolate",
          ["linear"],
          ["zoom"],
          3,
          0.95,
          8,
          0.9,
          14,
          0.8,
        ],
      },
    },
    {
      id: "landcover-grass",
      type: "fill",
      source: "stadia",
      "source-layer": "landcover",
      minzoom: 5,
      filter: ["in", "class", "grass", "scrub"],
      paint: {
        "fill-color": m.grass,
        "fill-opacity": [
          "interpolate",
          ["linear"],
          ["zoom"],
          5,
          0.85,
          10,
          0.8,
          14,
          0.7,
        ],
      },
    },
    {
      id: "landuse-farmland",
      type: "fill",
      source: "stadia",
      "source-layer": "landuse",
      minzoom: 5,
      filter: ["in", "class", "farmland", "orchard", "vineyard"],
      paint: {
        "fill-color": m.farmland,
        "fill-opacity": [
          "interpolate",
          ["linear"],
          ["zoom"],
          5,
          0.7,
          10,
          0.6,
          14,
          0.5,
        ],
      },
    },
    {
      id: "landuse-residential",
      type: "fill",
      source: "stadia",
      "source-layer": "landuse",
      minzoom: 9,
      filter: ["==", "class", "residential"],
      paint: {
        "fill-color": m.residential,
        "fill-opacity": 0.5,
      },
    },
    {
      id: "landcover-park",
      type: "fill",
      source: "stadia",
      "source-layer": "landcover",
      minzoom: 8,
      filter: ["==", "class", "park"],
      paint: {
        "fill-color": m.park,
        "fill-opacity": 0.9,
      },
    },
    {
      id: "landuse-park",
      type: "fill",
      source: "stadia",
      "source-layer": "landuse",
      minzoom: 8,
      filter: ["in", "class", "park", "cemetery", "pitch"],
      paint: {
        "fill-color": m.park,
        "fill-opacity": 0.8,
      },
    },
    {
      id: "landcover-sand",
      type: "fill",
      source: "stadia",
      "source-layer": "landcover",
      filter: ["in", "class", "sand", "rock"],
      paint: {
        "fill-color": m.sand,
        "fill-opacity": 0.7,
      },
    },
    {
      id: "water",
      type: "fill",
      source: "stadia",
      "source-layer": "water",
      paint: {
        "fill-color": m.water,
        "fill-opacity": 1,
      },
    },
    {
      id: "waterway",
      type: "line",
      source: "stadia",
      "source-layer": "waterway",
      minzoom: 8,
      paint: {
        "line-color": m.waterway,
        "line-width": [
          "interpolate",
          ["linear"],
          ["zoom"],
          8,
          0.6,
          12,
          1.5,
          16,
          3,
        ],
        "line-opacity": 0.85,
      },
    },
    {
      id: "boundary-country",
      type: "line",
      source: "stadia",
      "source-layer": "boundary",
      filter: ["==", "admin_level", 2],
      minzoom: 3,
      paint: {
        "line-color": "#8a7f72",
        "line-width": ["interpolate", ["linear"], ["zoom"], 3, 0.6, 8, 1.4],
        "line-opacity": 0.55,
        "line-dasharray": [3, 2],
      },
    },

    // --- ROAD CASINGS ---
    {
      id: "road-motorway-casing",
      type: "line",
      source: "stadia",
      "source-layer": "transportation",
      minzoom: 3,
      filter: ["==", "class", "motorway"],
      layout: { "line-join": "round", "line-cap": "round" },
      paint: {
        "line-color": m.motorwayCasing,
        "line-width": [
          "interpolate",
          ["linear"],
          ["zoom"],
          3,
          1.8,
          5,
          3,
          8,
          5,
          12,
          9,
          16,
          16,
        ],
      },
    },
    {
      id: "road-trunk-casing",
      type: "line",
      source: "stadia",
      "source-layer": "transportation",
      minzoom: 3,
      filter: ["==", "class", "trunk"],
      layout: { "line-join": "round", "line-cap": "round" },
      paint: {
        "line-color": m.trunkCasing,
        "line-width": [
          "interpolate",
          ["linear"],
          ["zoom"],
          3,
          1.4,
          5,
          2.4,
          9,
          4,
          13,
          8.5,
          16,
          13,
        ],
      },
    },
    {
      id: "road-primary-casing",
      type: "line",
      source: "stadia",
      "source-layer": "transportation",
      minzoom: 4,
      filter: ["==", "class", "primary"],
      layout: { "line-join": "round", "line-cap": "round" },
      paint: {
        "line-color": m.primaryCasing,
        "line-width": [
          "interpolate",
          ["linear"],
          ["zoom"],
          4,
          1.2,
          6,
          2,
          10,
          4,
          14,
          9,
          16,
          12,
        ],
      },
    },
    {
      id: "road-secondary-casing",
      type: "line",
      source: "stadia",
      "source-layer": "transportation",
      minzoom: 7,
      filter: ["in", "class", "secondary", "tertiary"],
      layout: { "line-join": "round", "line-cap": "round" },
      paint: {
        "line-color": m.secondaryCasing,
        "line-width": [
          "interpolate",
          ["linear"],
          ["zoom"],
          7,
          1.3,
          10,
          2.6,
          13,
          4.5,
          16,
          9,
        ],
        "line-opacity": [
          "interpolate",
          ["linear"],
          ["zoom"],
          7,
          0.75,
          9,
          1,
        ],
      },
    },
    {
      id: "road-minor-casing",
      type: "line",
      source: "stadia",
      "source-layer": "transportation",
      minzoom: 9,
      filter: ["in", "class", "minor", "unclassified"],
      layout: { "line-join": "round", "line-cap": "round" },
      paint: {
        "line-color": m.minorCasing,
        "line-width": [
          "interpolate",
          ["linear"],
          ["zoom"],
          9,
          1.1,
          12,
          2.4,
          15,
          5,
          17,
          8,
        ],
        "line-opacity": [
          "interpolate",
          ["linear"],
          ["zoom"],
          9,
          0.55,
          11,
          0.85,
          13,
          1,
        ],
      },
    },
    {
      id: "road-residential-casing",
      type: "line",
      source: "stadia",
      "source-layer": "transportation",
      minzoom: 11,
      filter: ["in", "class", "residential", "service"],
      layout: { "line-join": "round", "line-cap": "round" },
      paint: {
        "line-color": m.minorCasing,
        "line-width": [
          "interpolate",
          ["linear"],
          ["zoom"],
          11,
          1.2,
          14,
          3.2,
          17,
          7,
        ],
        "line-opacity": [
          "interpolate",
          ["linear"],
          ["zoom"],
          11,
          0.45,
          13,
          0.85,
          14,
          1,
        ],
      },
    },

    // --- ROAD FILLS (lighter than casing) ---
    {
      id: "road-motorway",
      type: "line",
      source: "stadia",
      "source-layer": "transportation",
      minzoom: 3,
      filter: ["==", "class", "motorway"],
      layout: { "line-join": "round", "line-cap": "round" },
      paint: {
        "line-color": m.motorwayFill,
        "line-width": [
          "interpolate",
          ["linear"],
          ["zoom"],
          3,
          1,
          5,
          1.8,
          8,
          3.2,
          12,
          6.5,
          16,
          12.5,
        ],
      },
    },
    {
      id: "road-trunk",
      type: "line",
      source: "stadia",
      "source-layer": "transportation",
      minzoom: 3,
      filter: ["==", "class", "trunk"],
      layout: { "line-join": "round", "line-cap": "round" },
      paint: {
        "line-color": m.trunkFill,
        "line-width": [
          "interpolate",
          ["linear"],
          ["zoom"],
          3,
          0.8,
          5,
          1.4,
          9,
          2.8,
          13,
          6,
          16,
          10,
        ],
      },
    },
    {
      id: "road-primary",
      type: "line",
      source: "stadia",
      "source-layer": "transportation",
      minzoom: 4,
      filter: ["==", "class", "primary"],
      layout: { "line-join": "round", "line-cap": "round" },
      paint: {
        "line-color": m.primaryFill,
        "line-width": [
          "interpolate",
          ["linear"],
          ["zoom"],
          4,
          0.7,
          6,
          1.2,
          10,
          2.8,
          14,
          6.5,
          16,
          9.5,
        ],
      },
    },
    {
      id: "road-secondary-tertiary",
      type: "line",
      source: "stadia",
      "source-layer": "transportation",
      minzoom: 7,
      filter: ["in", "class", "secondary", "tertiary"],
      layout: { "line-join": "round", "line-cap": "round" },
      paint: {
        "line-color": m.secondaryFill,
        "line-width": [
          "interpolate",
          ["linear"],
          ["zoom"],
          7,
          0.7,
          10,
          1.6,
          13,
          3.2,
          16,
          7,
        ],
        "line-opacity": [
          "interpolate",
          ["linear"],
          ["zoom"],
          7,
          0.7,
          9,
          1,
        ],
      },
    },
    {
      id: "road-minor",
      type: "line",
      source: "stadia",
      "source-layer": "transportation",
      minzoom: 9,
      filter: ["in", "class", "minor", "unclassified"],
      layout: { "line-join": "round", "line-cap": "round" },
      paint: {
        "line-color": m.minorFill,
        "line-width": [
          "interpolate",
          ["linear"],
          ["zoom"],
          9,
          0.55,
          12,
          1.5,
          15,
          3.5,
          17,
          6,
        ],
        "line-opacity": [
          "interpolate",
          ["linear"],
          ["zoom"],
          9,
          0.5,
          11,
          0.85,
          13,
          1,
        ],
      },
    },
    {
      id: "road-residential",
      type: "line",
      source: "stadia",
      "source-layer": "transportation",
      minzoom: 11,
      filter: ["in", "class", "residential", "service"],
      layout: { "line-join": "round", "line-cap": "round" },
      paint: {
        "line-color": m.minorFill,
        "line-width": [
          "interpolate",
          ["linear"],
          ["zoom"],
          11,
          0.6,
          14,
          2.2,
          17,
          5.5,
        ],
        "line-opacity": [
          "interpolate",
          ["linear"],
          ["zoom"],
          11,
          0.4,
          13,
          0.85,
          14,
          1,
        ],
      },
    },

    {
      id: "road-labels",
      type: "symbol",
      source: "stadia",
      "source-layer": "transportation_name",
      minzoom: 12,
      layout: {
        "text-field": textFr as unknown as string,
        "text-font": ["Noto Sans Regular"],
        "text-size": 11,
        "symbol-placement": "line",
      },
      paint: {
        "text-color": m.labelMuted,
        "text-halo-color": m.labelHalo,
        "text-halo-width": 1.5,
      },
    },

    // Tile place hierarchy (font Regular — Bold often missing in Stadia glyphs)
    {
      id: "label-country",
      type: "symbol",
      source: "stadia",
      "source-layer": "place",
      filter: ["==", "class", "country"],
      maxzoom: 7,
      layout: {
        "text-field": textFr as unknown as string,
        "text-font": ["Noto Sans Regular"],
        "text-size": ["interpolate", ["linear"], ["zoom"], 3, 13, 6, 18],
        "text-transform": "uppercase",
        "text-letter-spacing": 0.08,
      },
      paint: {
        "text-color": m.labelMuted,
        "text-halo-color": m.labelHalo,
        "text-halo-width": 1.8,
        "text-opacity": 0.75,
      },
    },
    {
      id: "label-city-tile",
      type: "symbol",
      source: "stadia",
      "source-layer": "place",
      minzoom: 5,
      filter: [
        "all",
        ["==", "class", "city"],
        ["<=", "rank", 8],
      ],
      layout: {
        "text-field": textFr as unknown as string,
        "text-font": ["Noto Sans Regular"],
        "text-size": ["interpolate", ["linear"], ["zoom"], 5, 12, 10, 16],
        "text-padding": 4,
      },
      paint: {
        "text-color": m.label,
        "text-halo-color": m.labelHalo,
        "text-halo-width": 2,
      },
    },
    {
      id: "label-town-tile",
      type: "symbol",
      source: "stadia",
      "source-layer": "place",
      minzoom: 8,
      filter: ["==", "class", "town"],
      layout: {
        "text-field": textFr as unknown as string,
        "text-font": ["Noto Sans Regular"],
        "text-size": ["interpolate", ["linear"], ["zoom"], 8, 11, 12, 14],
      },
      paint: {
        "text-color": m.labelMuted,
        "text-halo-color": m.labelHalo,
        "text-halo-width": 1.6,
      },
    },

    // Guaranteed French landmarks (Paris, Bordeaux, Lille, …)
    {
      id: "label-fr-landmarks",
      type: "symbol",
      source: "fr-landmarks",
      minzoom: 4,
      maxzoom: 12,
      layout: {
        "text-field": ["get", "name"],
        "text-font": ["Noto Sans Regular"],
        "text-size": [
          "interpolate",
          ["linear"],
          ["zoom"],
          4,
          ["match", ["get", "rank"], 1, 13, 11],
          8,
          ["match", ["get", "rank"], 1, 16, 13],
          11,
          ["match", ["get", "rank"], 1, 18, 14],
        ],
        "text-padding": 2,
        "text-allow-overlap": false,
        "symbol-sort-key": ["get", "rank"],
      },
      paint: {
        "text-color": m.label,
        "text-halo-color": m.labelHalo,
        "text-halo-width": 2.2,
      },
    },
  ],
};

export default mapStyle;
